---
title: "Dry_mixed_deciduous_forest"
author: "ONeill"
date: "June 15, 2018"
output: html_document
---
```{r}
rm(list = ls())

# install.packages("tidyverse")
# install.packages("lubridate")
# install.packages("BIOMASS")

library(tidyverse)
library(lubridate)
library(BIOMASS)

```
```{r}

Dry_mixed_deciduous_forest <- read.csv("../../Data/Dry_mixed_deciduous_forest.csv")


head(Dry_mixed_deciduous_forest)
str(Dry_mixed_deciduous_forest)
```
```{r}

Taxo <- correctTaxo(genus=Dry_mixed_deciduous_forest$Genus,species = Dry_mixed_deciduous_forest$Species)

Dry_mixed_deciduous_forest$genusCorr <- Taxo$genusCorrected
Dry_mixed_deciduous_forest$speciesCorr <- Taxo$speciesCorrected

APG <- getTaxonomy(Dry_mixed_deciduous_forest$genusCorr, findOrder =T)
Dry_mixed_deciduous_forest$familyAPG <- APG$family
Dry_mixed_deciduous_forest$orderAPG <- APG$order

dataWD <- getWoodDensity(genus=Dry_mixed_deciduous_forest$genusCorr,
                       species=Dry_mixed_deciduous_forest$speciesCorr,
                       stand=Dry_mixed_deciduous_forest$plotId)

sum(dataWD$levelWD == "species")

sum(dataWD$levelWD == "genus")

sum(!dataWD$levelWD%in%c("genus","species"))

Dry_mixed_deciduous_forest$WD <-  dataWD$meanWD 
print(Dry_mixed_deciduous_forest)
str(Dry_mixed_deciduous_forest)
is.na(Dry_mixed_deciduous_forest$H_m)
```
# Develop HD model
```{r}
HDmodels <- modelHD(D=Dry_mixed_deciduous_forest$Dbh_cm, 
                   H = Dry_mixed_deciduous_forest$H_m,
                   drawGraph=TRUE,
                   useWeight=TRUE)

Best_HDmodel<- modelHD(D=Dry_mixed_deciduous_forest$Dbh_cm,
                 H=Dry_mixed_deciduous_forest$H_m,
                 method="log3",
                 useWeight =TRUE)


```
# Getting missing tree Height
```{r}
dataHlocal<-retrieveH(D=Dry_mixed_deciduous_forest$Dbh_cm[is.na(Dry_mixed_deciduous_forest$H_m)],
                      model = Best_HDmodel)
Dry_mixed_deciduous_forest$H_m[is.na(Dry_mixed_deciduous_forest$H_m)] <- dataHlocal$H

```


# Estimate Biomass
```{r}
Dry_mixed_deciduous_forest$AGB <-computeAGB(D=Dry_mixed_deciduous_forest$Dbh_cm,
                    WD=Dry_mixed_deciduous_forest$WD,
                    H=Dry_mixed_deciduous_forest$H_m)



DMDF <- Dry_mixed_deciduous_forest

```

#Estimate Biomass_ha

```{r}
plot_agb<-DMDF %>%
  group_by(Plot_id) %>%
  summarise(AGB_total = sum(AGB)) %>%
  mutate(AGB_ha = AGB_total*(1/0.16))


hist(plot_agb$AGB_ha)
mean(plot_agb$AGB_ha); median(plot_agb$AGB_ha)
```




